trigger:
  branches:
    [main]

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: foodforlife-variable-group
  - template: ci-vars-template.yml

steps:
  - template: ci-steps-template.yml