name: CD Pipeline- Helm and AKS

trigger: none
resources:
  pipelines:
    - pipeline: foodforlife-release-pipeline
      source: foodforlife-ci-pipeline
      trigger: true

pr: none
variables:
  - group: foodforlife-variable-group
  - template: cd-vars-template.yml
stages:
  - stage: test
    displayName: test
    jobs:
      - deployment: test
        variables:
          - group: foodforlife-variable-group
        displayName: deploy helm chart into AKS
        pool:
          vmImage: ubuntu-latest
        environment: test-$(projectName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: cd-steps-template.yml
