name: CD Pipeline- Helm and AKS

trigger: none
resources:
  pipelines:
    pipeline: release-pipeline 
    source: foodforlife-sreejith824.producers-api-platform
    trigger:
    branches:
      include:
        - main

pr: none

# define variables: registryName, registryLogin and registryPassword in the Azure pipeline UI definition
variables:
  - group: foodforlife-variable-group
  - template: cd-vars-template.yml

# define 5 variables: aks, rg, aksSpId, aksSpSecret and aksSpTenantId in the Azure pipeline UI definition
stages:
  - stage: test
    displayName: test
    jobs:
      - deployment: test
        variables:
          - group: foodforlife-variable-group
        displayName: deploy helm chart into AKS
        pool:
          vmImage: ubuntu-latest
        environment: test-$(projectName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: cd-steps-template.yml