
steps:
  - checkout: none
  - task: HelmInstaller@1
    displayName: "install helm"

  # Set the target Azure Kubernetes Service (AKS) cluster. 
  - name: "Set AKS context and login"
    uses: azure/aks-set-context@v1
    with:
      creds: "$(AZURE_CREDENTIALS)"
      cluster-name: $(CLUSTER_NAME)
      resource-group: $(CLUSTER_RESOURCE_GROUP)  

  - bash: |

       echo $(ACR_HELM_SP_PASSWORD) | helm registry login $(ACR_SERVER_NAME) --username $(ACR_HELM_SP_USERNAME) --password-stdin

       helm chart pull $(ACR_SERVER_NAME)/$(HELM_CHART):latest
       helm chart export $(ACR_SERVER_NAME)/$(HELM_CHART):latest --destination $(pipeline.workspace)/install
       
       helm upgrade --namespace $(k8sNamespace) --create-namespace --install --wait  \
           --set image.repository=$(ACR_SERVER_NAME)/$(HELM_CHART) \
           -f $(pipeline.workspace)/templates/deployment.yaml \
           -f $(pipeline.workspace)/templates/service.yaml \
           $(projectName) \
           $(pipeline.workspace)/install/$(projectName)
    failOnStderr: true
    displayName: "deploy helm chart"